# Generated by Django 3.0.6 on 2020-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotitle',
            name='api_id',
            field=models.IntegerField(default=1),
        ),
    ]
